import type { FeedMusician, FeedVenue } from './types'

export const DEMO_MUSICIANS: FeedMusician[] = [
  {
    id: 'demo-m1',
    stage_name: 'Neon Velvet',
    bio: "Electronic producer blending synthwave and deep house. Residency at Stubb's every Friday.",
    genre: ['EDM'],
    city: 'Austin', state: 'TX',
    hourly_rate: 350,
    spotify_url: 'https://open.spotify.com/artist/example',
    youtube_url: null,
    profile_image: null,
    is_available: true,
  },
  {
    id: 'demo-m2',
    stage_name: 'The Lone Star Collective',
    bio: 'Six-piece country outfit with three-part harmonies and outlaw spirit. Born on 6th Street.',
    genre: ['Country'],
    city: 'Austin', state: 'TX',
    hourly_rate: 275,
    spotify_url: null,
    youtube_url: null,
    profile_image: null,
    is_available: true,
  },
  {
    id: 'demo-m3',
    stage_name: 'Marcus Reel',
    bio: 'Upright bassist and composer. Regular at the Elephant Room. Available for private events and sessions.',
    genre: ['Jazz'],
    city: 'Austin', state: 'TX',
    hourly_rate: 200,
    spotify_url: null,
    youtube_url: null,
    profile_image: null,
    is_available: true,
  },
  {
    id: 'demo-m4',
    stage_name: 'SOLARA',
    bio: 'Neo-soul vocalist with influences from Erykah Badu to Frank Ocean. Studio sessions and live bookings available.',
    genre: ['R&B'],
    city: 'Austin', state: 'TX',
    hourly_rate: 425,
    spotify_url: 'https://open.spotify.com/artist/example2',
    youtube_url: null,
    profile_image: null,
    is_available: true,
  },
  {
    id: 'demo-m5',
    stage_name: 'Dustin Hale Band',
    bio: 'Traditional Texas blues with a modern edge. 15 years on the circuit, available weekends.',
    genre: ['Blues'],
    city: 'Austin', state: 'TX',
    hourly_rate: 180,
    spotify_url: null,
    youtube_url: null,
    profile_image: null,
    is_available: true,
  },
  {
    id: 'demo-m6',
    stage_name: 'Crux',
    bio: 'Four-piece rock band. Think Foo Fighters meets Arctic Monkeys. High energy live show.',
    genre: ['Rock'],
    city: 'Austin', state: 'TX',
    hourly_rate: 300,
    spotify_url: null,
    youtube_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    profile_image: null,
    is_available: true,
  },
  {
    id: 'demo-m7',
    stage_name: 'DJ Phantom',
    bio: 'Hip-hop DJ and producer. Corporate events, weddings, and club nights. 10 years experience.',
    genre: ['Hip-Hop'],
    city: 'Austin', state: 'TX',
    hourly_rate: 250,
    spotify_url: null,
    youtube_url: null,
    profile_image: null,
    is_available: true,
  },
  {
    id: 'demo-m8',
    stage_name: 'Luna Reyes',
    bio: 'Flamenco and Latin jazz fusion. Available for restaurant residencies and private events.',
    genre: ['Latin'],
    city: 'Austin', state: 'TX',
    hourly_rate: 220,
    spotify_url: null,
    youtube_url: null,
    profile_image: null,
    is_available: true,
  },
]

export const DEMO_VENUES: FeedVenue[] = [
  {
    id: 'demo-v1',
    name: 'The Velvet Underground ATX',
    bio: 'Intimate dark venue on Red River. Perfect for indie, jazz, and electronic acts. Full bar and green room.',
    city: 'Austin', state: 'TX',
    capacity: 300,
    profile_image: null,
  },
  {
    id: 'demo-v2',
    name: 'Lone Star Amphitheater',
    bio: 'Outdoor amphitheater off South Congress. Hosts 200+ events per year. Full production team on site.',
    city: 'Austin', state: 'TX',
    capacity: 2500,
    profile_image: null,
  },
  {
    id: 'demo-v3',
    name: 'Parish ATX',
    bio: 'Historic venue on 6th Street. Known for rock, blues, and soul. Legendary sound system.',
    city: 'Austin', state: 'TX',
    capacity: 500,
    profile_image: null,
  },
  {
    id: 'demo-v4',
    name: "Cheer Up Charlies",
    bio: "Beloved outdoor patio venue. LGBTQ+ friendly, eclectic booking across all genres.",
    city: 'Austin', state: 'TX',
    capacity: 400,
    profile_image: null,
  },
  {
    id: 'demo-v5',
    name: "Antone's Nightclub",
    bio: "Austin's home of the blues since 1975. Iconic stage, world-class talent, unforgettable nights.",
    city: 'Austin', state: 'TX',
    capacity: 600,
    profile_image: null,
  },
]

// Subset with media links for the "New Music" row
export const DEMO_MUSICIANS_WITH_MEDIA = DEMO_MUSICIANS.filter(
  m => m.spotify_url || m.youtube_url
)
